# Generated by Django 4.2.5 on 2023-12-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_hides', '0002_birdspots'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
