# Generated by Django 5.0 on 2023-12-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_hides', '0003_birdlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdlocation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
